START/WAIT python -m pip install --upgrade pip
START/WAIT python -m pip install --upgrade virtualenv
START/WAIT python -m pip install --upgrade python
START/WAIT python -m pip install --upgrade setuptools
START/WAIT python -m pip install --upgrade matplotlib
START/WAIT python -m pip install --upgrade Cython
START/WAIT python -m pip install --upgrade Nose
START/WAIT python -m pip install --upgrade Tempita
START/WAIT python -m pip install --upgrade mkl
START/WAIT python -m pip install --upgrade numpy
START/WAIT python -m pip install --upgrade SciPy
START/WAIT python -m pip install --upgrade scikit-learn[alldeps]
START/WAIT python -m pip install --upgrade pandas
START/WAIT python -m pip install --upgrade math
START/WAIT python -m pip install --upgrade abc